package com.security.anomaly.service;

import com.security.anomaly.model.*;
import com.security.anomaly.repository.AlertRepository;
import com.security.anomaly.repository.LoginLogRepository;
import com.security.anomaly.repository.UserRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.ResponseEntity;
import org.springframework.stereotype.Service;
import org.springframework.web.client.RestTemplate;

import java.time.LocalTime;
import java.util.Optional;

@Service
public class AuthService {

    @Autowired
    private UserRepository userRepository;

    @Autowired
    private LoginLogRepository loginLogRepository;

    @Autowired
    private AlertRepository alertRepository;

    private final RestTemplate restTemplate = new RestTemplate();
    private final String mlApiUrl = "http://127.0.0.1:8000/predict";

    public String login(LoginRequest request) {
        Optional<User> userOpt = userRepository.findByUsername(request.getUsername());
        
        if (userOpt.isEmpty()) {
            return "User not found";
        }
        
        User user = userOpt.get();
        
        // Ensure inputs aren't completely null to avoid issues
        String deviceInfo = request.getDeviceInfo() != null ? request.getDeviceInfo() : "unknown";
        String ipAddress = request.getIpAddress() != null ? request.getIpAddress() : "0.0.0.0";

        // Calculate features for ML
        int currentHour = LocalTime.now().getHour();
        int failedAttempts = loginLogRepository.countFailedAttempts(user.getId(), 24);
        boolean isNewDevice = loginLogRepository.isNewDevice(user.getId(), deviceInfo);
        boolean isNewIp = loginLogRepository.isNewIp(user.getId(), ipAddress);

        // Call ML service
        MLPredictionRequest mlReq = new MLPredictionRequest();
        mlReq.setUserId(user.getId());
        mlReq.setLoginHour(currentHour);
        mlReq.setFailedAttempts(failedAttempts);
        mlReq.setIsNewDevice(isNewDevice ? 1 : 0);
        mlReq.setIsNewIp(isNewIp ? 1 : 0);

        Double anomalyScore = 0.0;
        boolean isAnomalous = false;

        try {
            ResponseEntity<MLPredictionResponse> response = restTemplate.postForEntity(mlApiUrl, mlReq, MLPredictionResponse.class);
            if (response.getBody() != null) {
                anomalyScore = response.getBody().getAnomalyScore();
                isAnomalous = response.getBody().getIsAnomalous() == 1;
            }
        } catch (Exception e) {
            System.err.println("Failed to reach ML API: " + e.getMessage());
        }

        // Simulating login logic (always success for this prototype to observe logs)
        boolean loginSuccess = true; 

        // Store login log
        LoginLog log = new LoginLog();
        log.setUserId(user.getId());
        log.setIpAddress(ipAddress);
        log.setDeviceInfo(deviceInfo);
        log.setSuccess(loginSuccess);
        log.setAnomalyScore(anomalyScore);
        log.setAnomalous(isAnomalous);
        
        loginLogRepository.save(log);

        // Note: For alerting, we need the inserted log's id, but for simplicity here we just store the alert without log id or fetch the latest log.
        // In a real app we'd use KeyHolder in JDBC to get the autogenerated ID.
        if (isAnomalous) {
            Alert alert = new Alert();
            alert.setUserId(user.getId());
            alert.setAlertType("Anomalous Login Detected");
            alert.setSeverity(anomalyScore > 1.5 ? "HIGH" : "MEDIUM");
            alertRepository.save(alert);
        }

        return loginSuccess ? "Login successful" : "Login failed";
    }

    public String simulateAttack() {
        System.out.println("Simulating attack events...");
        int eventCount = 10;
        java.util.Random random = new java.util.Random();
        
        long[] userIds = {1L, 2L, 3L, 4L, 5L};
        String[] unusualIps = {"185.234.21.11", "103.55.22.19", "45.77.10.3"};
        String[] unusualDevices = {"UnknownBrowser", "TorBrowser", "BotAgent"};
        
        for (int i = 0; i < eventCount; i++) {
            Long userId = userIds[random.nextInt(userIds.length)];
            String ip = unusualIps[random.nextInt(unusualIps.length)];
            String device = unusualDevices[random.nextInt(unusualDevices.length)];
            
            // Generate unusual login times (late night hours, e.g., 1 AM to 4 AM)
            int hour = 1 + random.nextInt(4);
            int failedAttempts = 3 + random.nextInt(5);
            
            // Call ML service
            MLPredictionRequest mlReq = new MLPredictionRequest();
            mlReq.setUserId(userId);
            mlReq.setLoginHour(hour);
            mlReq.setFailedAttempts(failedAttempts);
            mlReq.setIsNewDevice(1);
            mlReq.setIsNewIp(1);
            
            Double anomalyScore = 0.0;
            boolean isAnomalous = false;
            
            try {
                ResponseEntity<MLPredictionResponse> response = restTemplate.postForEntity(mlApiUrl, mlReq, MLPredictionResponse.class);
                if (response.getBody() != null) {
                    anomalyScore = response.getBody().getAnomalyScore();
                    // Mark event as anomalous if score > 1.0 per requirement
                    isAnomalous = anomalyScore > 1.0;
                }
            } catch (Exception e) {
                anomalyScore = 2.0 + random.nextDouble();
                isAnomalous = true;
            }
            
            // Save Log
            LoginLog log = new LoginLog();
            log.setUserId(userId);
            log.setIpAddress(ip);
            log.setDeviceInfo(device);
            log.setSuccess(false); // typically an attack is a failed login
            log.setAnomalyScore(anomalyScore);
            log.setAnomalous(isAnomalous);
            
            loginLogRepository.save(log);
            
            // Save Alert
            if (isAnomalous) {
                // Approximate ID linkage by finding last insert
                Alert alert = new Alert();
                alert.setUserId(userId);
                alert.setAlertType("Simulated Attack Detected");
                alert.setSeverity("HIGH");
                alertRepository.save(alert);
            }
        }
        
        System.out.println("10 suspicious login attempts generated");
        System.out.println("ML predictions completed");
        return "Simulated " + eventCount + " attack events.";
    }
}
